### ISSUE TITLE
"Could not find function" Error

### ISSUE THREAD

**Issue by AbelGalois** [khufkens/amerifluxr#1]
Hi, Hufkens! Thanks for your sharing. But after I installed the package and tested it, I got an error that told me "could not find function "ameriflux.explorer"". I already found the folder "amerifluxr" on my laptop. I'm afraid I missed something. Could you provide some suggestions for checking what is the matter? Thanks!
(below is a screenshot)
<img width="716" alt="screen shot 2016-03-15 at 20 39 35" src="https://cloud.githubusercontent.com/assets/17846818/13778019/44df02fa-eaee-11e5-9fbe-b144f7529c9e.png">

**Comment by khufkens** [comment]
load the library using:
library(amerifluxr) or require(amerifluxr)

**Comment by AbelGalois** [comment]
Oh,yeah, many thanks! I'm a green hand here...
